#PBS -l nodes=4:ppn=28:gpus=1:default
#PBS -j oe
#PBS -A PAS1090
#PBS -m f
#PBS -S /bin/bash

cd ${PBS_O_WORKDIR}
pwd
source activate tfgpu
module load cuda/9.0.176
echo "python ../tf/examples/EMI-RNN/step2_emi_fastrgnn_disp_det.py -Dat $Dat -O $O -ots $ots -k $k -ep $ep -it $it -rnd $rnd"
python ../tf/examples/EMI-RNN/step2_emi_fastrgnn_disp_det.py -Dat $Dat -O $O -ots $ots -k $k -ep $ep -it $it -rnd $rnd
